### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by arugondashiva** [jagan103/DDos-SDN#1]
When i start learning module i am getting the following errors, can u please help me out.
Thankyou

mininet@mininet-vm:~/pox$ python ./pox.py forwarding.l3_learning.py
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
Traceback (most recent call last):
  File "/home/mininet/pox/pox/boot.py", line 91, in do_import2
    __import__(name, level=0)
  File "/home/mininet/pox/pox/forwarding/l3_learning.py", line 45, in <module>
    from .detection import Entropy
  File "/home/mininet/pox/pox/forwarding/detection.py", line 21
    print 'Entropy=',sum(entropylist)
        ^
SyntaxError: invalid syntax
Could not import module: forwarding.l3_learning.py

**Comment by jagan103** [comment]
the issue as been resolved

**Comment by arugondashiva** [comment]
Hi bro, thanks for ur time :)
When i tested the l3_editing controller with ddos attack, i am getting most of the entropy values as 0's. Is that because, i am attacking at high rates and all the time entropy value is 0. And after stopping the attack also i am getting 0 as entropy value. can u please suggest me any changes. 
I am getting like this:
2018-11-26 00:07:01.536465 : printing diction  {1: {1: 1}} 

INFO:forwarding.l3_editing:1 1 RE-learned 0.0.0.0
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
DEBUG:forwarding.l3_editing:1 3 IP 0.0.0.0 => 255.255.255.255

***** Entropy Value =  0.0 *****

('Enpty diction ', '1', '3')

2018-11-26 00:07:04.131127 : printing diction  {1: {3: 1}} 

INFO:forwarding.l3_editing:1 3 RE-learned 0.0.0.0
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
DEBUG:forwarding.l3_editing:1 2 IP 0.0.0.0 => 255.255.255.255

***** Entropy Value =  0.0 *****

('Enpty diction ', '1', '2')

2018-11-26 00:07:05.206514 : printing diction  {1: {2: 1}} 

INFO:forwarding.l3_editing:1 2 RE-learned 0.0.0.0
INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
DEBUG:forwarding.l3_editing:3 4 IP 0.0.0.0 => 255.255.255.255

***** Entropy Value =  0.0 *****

('Enpty diction ', '3', '4')

2018-11-26 00:07:07.386990 : printing diction  {3: {4: 1}} 

INFO:packet:(dhcp parse) warning DHCP packet data too short to parse header: data len 86
DEBUG:forwarding.l3_editing:4 4 IP 0.0.0.0 => 255.255.255.255

***** Entropy Value =  0.0 *****

('Enpty diction ', '4', '4')

**Comment by saminresearch** [comment]
![4](https://user-images.githubusercontent.com/64364735/113826901-7f3bfa80-97a4-11eb-93b1-0b13dc3f8e51.PNG)

I am facing a similar issue. Can you tell me what am I doing wrong?

**Comment by nyakukweni** [comment]
hello @jagan103, I am facing this same issue. I noticed you mentioned that the issue was resolved, so what should we do to resolve this error.

Thank you

**Comment by astusdn2121** [comment]
> the issue as been resolved

i have face the same issue how u resolve it bro thanks

**Comment by astusdn2121** [comment]
either any one help  please...please ..i tried so many times but i canot solve it please help me 
File "/home/mininet/pox/pox/boot.py", line 74, in do_import2
    __import__(name, level=0)

  File "/home/mininet/pox/pox/forwarding/l3_learning_editted_final.py", line 45, in <module>
    from detection import Entropy
ModuleNotFoundError: No module named 'detection'
Could not import module: forwarding.l3_learning_editted_final
