### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by ANJUKOTTAKKAL** [jagan103/DDos-SDN#2]
sir,
When I am running the python launchTraffic.py –f 2 –l 65 command on xtrem window of host h1 ,I found an error which is giver below.
line 16
 if opts,  args = getopt.getopt(sys.argv[1:],'f:l:',['first=','last='])
            ^

syntax error : Invalid Syntax.

please help me to solve these problem.

**Comment by jagan103** [comment]
Hi anjukottakkal,
Thanks for letting me know, 
use -f 2 -e 65 instead of -f 2 -l 65
as i used 'e' for indicating ending number of host

**Comment by ANJUKOTTAKKAL** [comment]
Sorry, it's not working ....
The  same error occurs in again.

**Comment by jagan103** [comment]
Have you modified the l3 part of pox controller? 
Attach the screenshot of error.
